HAI
BTW checking input
VISIBLE "Write a number:"
I HAS A VAR
GIMMEH VAR
VAR IS NOW A NUMBR
VISIBLE "Sum of your number and 20:"
VISIBLE SUM OF VAR AN 20
VAR IS NOW A YARN
VISIBLE "Write a string"
GIMMEH VAR
VISIBLE "Sum of two strings"
VISIBLE SUM OF VAR AN VAR
KTHXBYE
